scala> try 1
-- Warning:
1 | try 1
  | ^^^^^
  | A try without catch or finally is equivalent to putting
  | its body in a block; no exceptions are handled.
val res0: Int = 1
